"""London Luton Airport (LTN) destinations — May 2026."""

DESTINATIONS = {
    "LTN": {
        "name": "London Luton",
        "routes": {
            "ABZ": "Aberdeen",
            "ACE": "Lanzarote",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCM": "Bacau",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast",
            "BGY": "Milan Bergamo",
            "BJV": "Bodrum",
            "BLQ": "Bologna",
            "BOJ": "Burgas",
            "BSL": "Basel",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "BZG": "Bydgoszcz",
            "BZR": "Beziers",
            "CCF": "Carcassonne",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CHQ": "Chania",
            "CLJ": "Cluj-Napoca",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DTM": "Dortmund",
            "DUB": "Dublin",
            "EDI": "Edinburgh",
            "EFL": "Kefalonia",
            "FAO": "Faro",
            "FCO": "Rome Fiumicino",
            "FNC": "Madeira",
            "FUE": "Fuerteventura",
            "GDN": "Gdansk",
            "GHV": "Brasov",
            "GLA": "Glasgow",
            "GNB": "Grenoble",
            "GVA": "Geneva",
            "HER": "Heraklion",
            "IAS": "Iasi",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "IST": "Istanbul",
            "JER": "Jersey",
            "JMK": "Mykonos",
            "JSI": "Skiathos",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KIR": "Kerry",
            "KRK": "Krakow",
            "KSC": "Kosice",
            "KTW": "Katowice",
            "KUN": "Kaunas",
            "LCA": "Larnaca",
            "LCJ": "Lodz",
            "LIS": "Lisbon",
            "LUZ": "Lublin",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MUC": "Munich",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "OLB": "Olbia",
            "OPO": "Porto",
            "ORK": "Cork",
            "OTP": "Bucharest",
            "PDV": "Plovdiv",
            "PFO": "Paphos",
            "PMI": "Palma",
            "PMO": "Palermo",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PRN": "Pristina",
            "PSA": "Pisa",
            "PUY": "Pula",
            "RAK": "Marrakech",
            "RBA": "Rabat",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "RMO": "Chisinau",
            "RMU": "Murcia",
            "RVN": "Rovaniemi",
            "RZE": "Rzeszow",
            "SBZ": "Sibiu",
            "SCV": "Suceava",
            "SJJ": "Sarajevo",
            "SKP": "Skopje",
            "SOF": "Sofia",
            "SPU": "Split",
            "SUJ": "Satu Mare",
            "SZG": "Salzburg",
            "SZY": "Szczytno",
            "TAT": "Poprad",
            "TFS": "Tenerife South",
            "TGM": "Targu Mures",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "TLL": "Tallinn",
            "TOS": "Tromso",
            "TSR": "Timisoara",
            "VAR": "Varna",
            "VCE": "Venice Marco Polo",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VNO": "Vilnius",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "ZRH": "Zurich",
            "ZTH": "Zakynthos",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
